-- Customize the qvOS look and feel here.

-- Example overrides:
-- hl.config({
--   general = {
--     gaps_in = 0,
--     gaps_out = 0,
--     border_size = 0,
--     layout = "scrolling",
--   },
--   decoration = {
--     rounding = 8,
--     dim_inactive = true,
--     dim_strength = 0.15,
--   },
--   animations = {
--     enabled = false,
--   },
--   scrolling = {
--     column_width = 0.97,
--   },
-- })
