# App-specific tweaks
source = ~/.local/share/qvos/default/hypr/apps/1password.conf
source = ~/.local/share/qvos/default/hypr/apps/bitwarden.conf
source = ~/.local/share/qvos/default/hypr/apps/browser.conf
source = ~/.local/share/qvos/default/hypr/apps/hyprshot.conf
source = ~/.local/share/qvos/default/hypr/apps/jetbrains.conf
source = ~/.local/share/qvos/default/hypr/apps/localsend.conf
source = ~/.local/share/qvos/default/hypr/apps/pip.conf
source = ~/.local/share/qvos/default/hypr/apps/qemu.conf
source = ~/.local/share/qvos/default/hypr/apps/retroarch.conf
source = ~/.local/share/qvos/default/hypr/apps/steam.conf
source = ~/.local/share/qvos/default/hypr/apps/geforce.conf
source = ~/.local/share/qvos/default/hypr/apps/moonlight.conf
source = ~/.local/share/qvos/default/hypr/apps/system.conf
source = ~/.local/share/qvos/default/hypr/apps/terminals.conf
source = ~/.local/share/qvos/default/hypr/apps/walker.conf
source = ~/.local/share/qvos/default/hypr/apps/webcam-overlay.conf
