# shellcheck shell=bash disable=SC1091

# If not running interactively, don't do anything (leave this at the top of this file)
[[ $- != *i* ]] && return

# All the default qvOS shell behavior
# (don't mess with these directly, just overwrite them here!)
source "$HOME/.local/share/qvos/qvcore/shell/files/rc"

# Add your own exports, aliases, and functions here.
#
# Make an alias for invoking commands you use constantly
# alias p='python'
