$orionActiveBorderColor = rgb(d00000)
$orionInactiveBorderColor = rgb(080808)
$orionTextColor = rgb(d0d0d0)
$orionMutedTextColor = rgb(707070)

general {
    gaps_in = 0
    gaps_out = 0
    float_gaps = 0
    border_size = 0

    col.active_border = $orionActiveBorderColor
    col.inactive_border = $orionInactiveBorderColor
    col.nogroup_border = $orionInactiveBorderColor
    col.nogroup_border_active = $orionActiveBorderColor

    resize_on_border = false
    extend_border_grab_area = 0
    hover_icon_on_border = false
    allow_tearing = false
}

decoration {
    rounding = 0
    active_opacity = 1.0
    inactive_opacity = 1.0
    fullscreen_opacity = 1.0

    shadow {
        enabled = false
    }

    blur {
        enabled = false
    }

    dim_inactive = true
    dim_strength = 0.08
}

group {
    col.border_active = $orionActiveBorderColor
    col.border_inactive = $orionInactiveBorderColor
    col.border_locked_active = $orionActiveBorderColor
    col.border_locked_inactive = $orionInactiveBorderColor

    groupbar {
        font_family = monospace
        font_weight_active = bold
        font_weight_inactive = normal
        font_size = 12

        gradients = false
        height = 20
        indicator_gap = 0
        indicator_height = 0
        gradient_rounding = 0
        gradient_round_only_edges = false

        text_color = $orionTextColor
        text_color_inactive = $orionMutedTextColor
        text_color_locked_active = $orionTextColor
        text_color_locked_inactive = $orionMutedTextColor

        col.active = rgba(00000000)
        col.inactive = rgba(00000000)
        col.locked_active = rgba(00000000)
        col.locked_inactive = rgba(00000000)

        gaps_out = 0
        gaps_in = 0
        text_padding = 6
        blur = false
    }
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    disable_scale_notification = true
    font_family = monospace
}
