#!/bin/bash

OMARCHY_PATH=${OMARCHY_PATH:-$HOME/.local/share/omarchy}
branding_owner="$OMARCHY_PATH/qv/branding/show-logo"

# shellcheck disable=SC2016
exec setsid uwsm-app -- \
  xdg-terminal-exec \
  --app-id=org.omarchy.terminal \
  --title=qvOS \
  -e bash -c \
  'branding_owner=$1
  shift
  "$branding_owner"
  "$@"
  status=$?
  if ((status == 0)); then
    omarchy-show-done
  elif ((status != 130)); then
    omarchy-show-failed "$status"
  fi
  exit "$status"' \
  _ "$branding_owner" "$@"
