#!/bin/bash
set -euo pipefail

share_state="$HOME/.local/state/qvos/qvcore/share"
if [[ -f $share_state ]]; then
  exit 0
fi

sudo ufw delete allow 53317/tcp >/dev/null 2>&1 || true
sudo ufw delete allow 53317/udp >/dev/null 2>&1 || true
