#!/bin/bash
set -euo pipefail

OMARCHY_PATH=${OMARCHY_PATH:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)}

"$OMARCHY_PATH/qvcore/boot/sync-theme" plymouth
sudo plymouth-set-default-theme omarchy
