#!/bin/bash
set -euo pipefail

QVOS_PATH=${QVOS_PATH:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)}

(( $# == 0 )) || {
  echo "Usage: ${0##*/}" >&2
  exit 2
}

"$QVOS_PATH/qvcore/boot/install-plymouth"
"$QVOS_PATH/qvcore/boot/install-sddm"
"$QVOS_PATH/qvcore/boot/install-limine-snapper"
