#!/bin/bash
set -euo pipefail

QVOS_PATH=${QVOS_PATH:-$HOME/.local/share/qvos}

(( $# == 0 )) || {
  echo "Usage: qv toggle suspend" >&2
  exit 2
}
exec "$QVOS_PATH/qvcore/config/toggle" \
  --enabled-notification "󰒲   Suspend removed from system menu" \
  --disabled-notification "󰒲   Suspend now available in system menu" \
  suspend-off
