#!/bin/bash
set -euo pipefail

omarchy-npx-install @openai/codex codex
# omarchy-npx-install @github/copilot copilot
omarchy-npx-install @earendil-works/pi-coding-agent pi
omarchy-npx-install @kitlangton/ghui ghui
