import { z } from "zod";

export const GameMediaSchema = z.object({
  logo: z.string().nullable(),
  boxArt: z.string().nullable(),
  artwork: z.string().nullable(),
  trailer: z.string().nullable(),
});

export const GameSchema = z.object({
  id: z.string().regex(/^[a-z0-9-]+$/),
  title: z.string().min(1),
  eyebrow: z.string().min(1),
  description: z.string().min(1),
  developer: z.string().min(1),
  publisher: z.string().min(1),
  tags: z.array(z.string().min(1)).min(1),
  media: GameMediaSchema,
  favorite: z.boolean(),
  lastPlayed: z.string().datetime().nullable(),
  tone: z.enum(["signal", "ember", "tide", "sky", "iron", "night", "graphite"]),
});

export type Game = z.infer<typeof GameSchema>;
export type GameMedia = z.infer<typeof GameMediaSchema>;

const rawGames = [
  {
    id: "the-last-signal",
    title: "The Last Signal",
    eyebrow: "Solo Play — Campaign",
    description:
      "Carry one impossible transmission across a city that has forgotten the sky. Every relay is silent, every route is watched, and the message changes the closer it gets to home.",
    developer: "Glass Relay",
    publisher: "Orion Works",
    tags: ["science fiction", "narrative", "exploration"],
    media: {
      logo: null,
      boxArt: "/art/the-last-signal.png",
      artwork: "/art/the-last-signal.png",
      trailer: null,
    },
    favorite: true,
    lastPlayed: "2026-07-17T19:24:00.000Z",
    tone: "signal",
  },
  {
    id: "ashen-circuit",
    title: "Ashen Circuit",
    eyebrow: "Solo Play — Campaign",
    description: "Wake the last salvage frame and walk it through a refinery still burning.",
    developer: "Foundry Nine",
    publisher: "Cinder Assembly",
    tags: ["mechs", "tactics", "industrial"],
    media: {
      logo: null,
      boxArt: "/art/ashen-circuit.png",
      artwork: "/art/ashen-circuit.png",
      trailer: null,
    },
    favorite: false,
    lastPlayed: "2026-07-11T22:10:00.000Z",
    tone: "ember",
  },
  {
    id: "black-tide",
    title: "Black Tide",
    eyebrow: "Solo Play — Campaign",
    description: "Keep the offshore signal alive while the sea dismantles everything around it.",
    developer: "Salt Frame",
    publisher: "Morrowline",
    tags: ["survival", "mystery", "ocean"],
    media: {
      logo: null,
      boxArt: "/art/black-tide.png",
      artwork: "/art/black-tide.png",
      trailer: null,
    },
    favorite: true,
    lastPlayed: "2026-07-15T01:42:00.000Z",
    tone: "tide",
  },
  {
    id: "hollow-sky",
    title: "Hollow Sky",
    eyebrow: "Solo Play — Campaign",
    description: "Cross the cloud ocean and learn why the habitat above it stopped answering.",
    developer: "Pale Atlas",
    publisher: "Altitude House",
    tags: ["exploration", "adventure", "atmospheric"],
    media: {
      logo: null,
      boxArt: "/art/hollow-sky.png",
      artwork: "/art/hollow-sky.png",
      trailer: null,
    },
    favorite: true,
    lastPlayed: "2026-07-08T18:09:00.000Z",
    tone: "sky",
  },
  {
    id: "iron-veil",
    title: "Iron Veil",
    eyebrow: "Solo Play — Skirmish",
    description: "Command a moving fortress across the salt flats before the next storm closes in.",
    developer: "Bastion Motor",
    publisher: "Red Mile",
    tags: ["strategy", "convoy", "simulation"],
    media: {
      logo: null,
      boxArt: "/art/iron-veil.png",
      artwork: "/art/iron-veil.png",
      trailer: null,
    },
    favorite: false,
    lastPlayed: "2026-06-29T16:32:00.000Z",
    tone: "iron",
  },
  {
    id: "night-protocol",
    title: "Night Protocol",
    eyebrow: "Solo Play — Campaign",
    description: "Follow a forbidden scan beneath the city and decide who gets to surface.",
    developer: "Sublevel",
    publisher: "Black Archive",
    tags: ["investigation", "stealth", "thriller"],
    media: {
      logo: null,
      boxArt: "/art/night-protocol.png",
      artwork: "/art/night-protocol.png",
      trailer: null,
    },
    favorite: true,
    lastPlayed: "2026-07-18T21:03:00.000Z",
    tone: "night",
  },
  {
    id: "static-bloom",
    title: "Static Bloom",
    eyebrow: "Solo Play — Journey",
    description: "A quiet machine garden waits for a frequency that may never return.",
    developer: "Soft Voltage",
    publisher: "Little Current",
    tags: ["puzzle", "ambient", "gardening"],
    media: {
      logo: null,
      boxArt: null,
      artwork: null,
      trailer: null,
    },
    favorite: false,
    lastPlayed: null,
    tone: "graphite",
  },
  {
    id: "null-meridian",
    title: "Null Meridian",
    eyebrow: "Solo Play — Campaign",
    description: "Chart the line where every compass fails and every message arrives twice.",
    developer: "Northless",
    publisher: "Dead Reckoning",
    tags: ["survey", "horror", "navigation"],
    media: {
      logo: null,
      boxArt: null,
      artwork: null,
      trailer: null,
    },
    favorite: false,
    lastPlayed: null,
    tone: "signal",
  },
] satisfies Game[];

export const games = z.array(GameSchema).parse(rawGames);
