# Orion Ghostty theme

background = #080808
foreground = #d0d0d0

palette = 0=#121212
palette = 1=#b00000
palette = 2=#707070
palette = 3=#8a8a8a
palette = 4=#a0a0a0
palette = 5=#b8b8b8
palette = 6=#909090
palette = 7=#c8c8c8

palette = 8=#404040
palette = 9=#d00000
palette = 10=#9a9a9a
palette = 11=#b0b0b0
palette = 12=#c6c6c6
palette = 13=#dddddd
palette = 14=#a8a8a8
palette = 15=#e6e6e6
