#!/bin/bash

# omarchy:summary=Refresh the SDDM theme from default
# omarchy:requires-sudo=true

sudo rm -rf /usr/share/sddm/themes/omarchy
sudo cp -r "$OMARCHY_PATH/qv/boot/sddm" /usr/share/sddm/themes/omarchy
