#!/bin/bash

# omarchy:summary=Overwrite the user config for the Limine bootloader and rebuild it.
# omarchy:requires-sudo=true

machine_id=$(</etc/machine-id)
extra_uki="/boot/EFI/Linux/${machine_id}_linux.efi"
if sudo test -f /boot/EFI/Linux/omarchy_linux.efi && sudo test -f "$extra_uki"; then
  echo "Cleanup extra UKI"
  sudo rm -f -- "$extra_uki"
fi
echo "Resetting limine config"

if sudo test -f /boot/limine.conf; then
  sudo cp -a -- \
    /boot/limine.conf \
    "/boot/limine.conf.bak.$(date +%s)"
fi
sudo install -m 0644 \
  "$OMARCHY_PATH/qv/boot/limine/limine.conf" \
  /boot/limine.conf

sudo limine-update
sudo limine-snapper-sync
