accent = "#b01616"
cursor = "#d0d0d0"
foreground = "#d0d0d0"
background = "#090909"
selection_foreground = "#090909"
selection_background = "#303030"

color0 = "#101010"
color1 = "#b01616"
color2 = "#707070"
color3 = "#8a8a8a"
color4 = "#a0a0a0"
color5 = "#b8b8b8"
color6 = "#909090"
color7 = "#c8c8c8"
color8 = "#404040"
color9 = "#d00000"
color10 = "#9a9a9a"
color11 = "#b0b0b0"
color12 = "#c6c6c6"
color13 = "#dddddd"
color14 = "#a8a8a8"
color15 = "#ffffff"
