#!/bin/bash
set -euo pipefail

THEME_NAME_PATH="$HOME/.config/qvos/current/theme.name"

if [[ -f $THEME_NAME_PATH ]]; then
  sed -E 's/(^|-)([a-z])/\1\u\2/g; s/-/ /g' "$THEME_NAME_PATH"
else
  echo "Unknown"
fi
