#!/bin/bash

set -euo pipefail

qv-cmd-present gsettings || exit 0

if [[ -f ~/.config/omarchy/current/theme/light.mode ]]; then
  gsettings set org.gnome.desktop.interface color-scheme "prefer-light"
  gsettings set org.gnome.desktop.interface gtk-theme "Adwaita"
else
  gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
  gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
fi

# Change gnome icon theme color
GNOME_ICONS_THEME="$HOME/.config/omarchy/current/theme/icons.theme"
if [[ -f $GNOME_ICONS_THEME ]]; then
  icon_theme=$(<"$GNOME_ICONS_THEME")
  [[ $icon_theme =~ ^[[:alnum:]][[:alnum:]_.+-]{0,127}$ ]] || {
    echo "Invalid icon theme name: $GNOME_ICONS_THEME" >&2
    exit 1
  }
  gsettings set org.gnome.desktop.interface icon-theme "$icon_theme"
else
  gsettings set org.gnome.desktop.interface icon-theme "Yaru-blue"
fi
